/* Inlines the four EyeMakkah Agent Bank files (assets/agent/*.json) into the
   single-file app as a compact AGENT_BANK, so the artifact stays self-contained.
   All 150 intents, every AR/EN example, keyword, response variant, the follow-up
   routing, confidence thresholds, contextual suggestions and alias groups are kept. */
import { readFile, writeFile, readdir } from "node:fs/promises";
const DIR = "assets/agent";
const files = (await readdir(DIR)).filter((f) => /^eyemakkah_app_agent_bank_\d+_.*\.json$/.test(f)).sort();
if (files.length !== 4) throw new Error(`expected 4 bank files in ${DIR}, found ${files.length}`);
const parts = await Promise.all(files.map(async (f) => JSON.parse(await readFile(`${DIR}/${f}`, "utf8"))));
const intents = parts.flatMap((p) => p.intents || []).map((it) => ({
  id: it.id,
  c: it.category,
  p: it.priority ?? 50,
  t: it.answer?.type || "fixed",
  h: it.answer?.handler || null,
  s: it.answer?.result_shape || null,
  ex: { ar: it.examples?.ar || [], en: it.examples?.en || [] },
  kw: { ar: it.matching?.keywords_ar || [], en: it.matching?.keywords_en || [] },
  en: it.matching?.entities || [],
  r: { ar: it.answer?.responses?.ar || [], en: it.answer?.responses?.en || [] },
  req: it.context?.required_context?.length ? it.context.required_context : null,
  fk: it.context?.followup_keys || [],
}));
const ids = new Set();
for (const it of intents) { if (ids.has(it.id)) throw new Error(`duplicate intent ${it.id}`); ids.add(it.id); }
const ctx = parts.find((p) => p.routing && p.aliases);
if (!ctx) throw new Error("context bank (routing/aliases) not found");
const bank = {
  version: parts.map((p) => `${p.part}@${p.version}`).join(" "),
  intents,
  routing: { followup_key_aliases: ctx.routing.followup_key_aliases, confidence: ctx.routing.confidence },
  suggestions: { by_page: ctx.contextual_suggestions.by_page, after_answer_type: ctx.contextual_suggestions.after_answer_type },
  aliases: ctx.aliases,
};
const START = "/* AGENT_BANK:start — generated by scripts/agent-sync.mjs from assets/agent/*.json; do not edit by hand */";
const END = "/* AGENT_BANK:end */";
const src = await readFile("EyeMakkah-app.jsx", "utf8");
const a = src.indexOf(START), b = src.indexOf(END);
if (a < 0 || b < 0) throw new Error("AGENT_BANK markers not found");
const block = `${START}\nconst AGENT_BANK = ${JSON.stringify(bank)};\n`;
await writeFile("EyeMakkah-app.jsx", src.slice(0, a) + block + src.slice(b));
const utter = intents.reduce((n, it) => n + it.ex.ar.length + it.ex.en.length, 0);
console.log(`AGENT_BANK: ${intents.length} intents, ${utter} example utterances, ${Object.keys(bank.aliases).length} alias groups inlined`);
